desc:Noteknob

slider1:11<1,16,1>Inc-Channel
slider2:12<1,16,1>Dec-Channel
slider3:1<1,16,1>Out-Channel
slider4:100<1,1000,1>Frequency (Hz)

@init
held_notes_inc = 0;
held_notes_dec = 0;
trigger_interval = srate / slider4;
sample_counter = 0;

@slider
trigger_interval = srate / slider4;

@block
sample_counter += samplesblock;
while (midirecv(offset, msg1, msg2, msg3)) (
  status = msg1 & 0xF0;
  channel = (msg1 & 0x0F) + 1;
  note = msg2;
  vel = msg3;

  is_inc = (channel == slider1);
  is_dec = (channel == slider2);
  handled = 0;

  (status == 0x90 && vel > 0) ? (
    (is_inc) ? (
      held_notes_inc[note] = 1;
      handled = 1
    );
    (is_dec) ? (
      held_notes_dec[note] = 1;
      handled = 1
    );
  );
    
  (status == 0x80 || (status == 0x90 && vel == 0)) ? (
    (is_inc) ? (
      held_notes_inc[note] = 0;
      handled = 1
    );
    (is_dec) ? (
      held_notes_dec[note] = 0;
      handled = 1
    );
  );

  (handled == 0) ? (
      midisend(offset, msg1, msg2, msg3);
  );
);

while (sample_counter >= trigger_interval) (
  sample_counter -= trigger_interval;
  
  n = 0;
  while (n < 128) (
    val = held_notes_inc[n];
    val != 0 ? (
      midisend(0, 0xB0 | (slider3 - 1), n, 1);
    );
    val = held_notes_dec[n];
    val != 0 ? (
      midisend(0, 0xB0 | (slider3 - 1), n, 127);
    );
    n += 1;
  );
);
